- name: variables 
  hosts: web 
  vars:
    my_name: "maha lakshmi"
    address: "Hyd"
  tasks:
  - name: display name and address   # variables represented by {{}}
    ansible.builtin.debug:
      msg: "Hi, I am {{ my_name }} and I am currently living in {{ address }}"
    

