- name: variables 
  hosts: web 
  vars:
    name: "maha lakshmi"
    address: "Hyd"
  tasks:
  - name: display name and address   # variables represented by {{}}
    ansible.buitlin.debug:
     msg: "Hi, I am {{ name }} and I am currently living in {{ address }}"
    

