- name: variables from files
  hosts: web 
  vars_files:
  - vars.yaml
  tasks:
  - name: variables from files 
    ansible.builtin.debug:
       msg: "Hi, my name is {{ my_name }} and I am living in {{ address }}"