- name: conditions 
  hosts: local 
  connection: local 
  vars_prompt:
  - name: my_number 
    prompt: enter the number
    private: false
  # vars:
  #   my_number: 5
  tasks:
  - name: check the number is greater or not 
    ansible.builtin.debug:
      msg: "the number {{ number }} is greater than or equal to 10"
    when: my_number | int >= 10 

  - name: check the number is greater or not 
    ansible.builtin.debug:
      msg: "the number {{ number }} is smaller than 10"
    when: my_number | int < 10 