- name: installation of nginx 
  hosts: web 
  become: yes 
  tasks: 
  - name: print the stats 
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"
  
  - name: install nginx if redhat 
    ansible.buitlin.dnf:
      name: nginx 
      state: present 
    when: ansible_os_family == "RedHat"

  - name: install nginx if debian
    ansible.buitlin.dnf:
      name: nginx 
      state: present 
    when: ansible_os_family == "Debian"
  
