- name: filters/functions 
  hosts: local 
  connection: local 
  tasks: 
  - name: print the default variables 
    ansible.builtin.debug:
      msg: "Hello {{ my_name | default('chinni') }}"   # here my_name is not defined earlier 


  - name: convert the string into uppercase 
    vars: 
      my_name: "chinni"
    ansible.builtin.debug:
     msg: "{{ my_name | upper }}"

  - name: convert the string into lowercase 
    vars: 
      my_name: "MAHA"
    ansible.builtin.debug:
     msg: "{{ my_name | lower }}"

  - name: print the unique numbers 
    vars: 
      numbers: [17,45,7,8,234,17,45,7,8,234,5,56,6,7,23,234]
    ansible.builtin.debug:
     msg: "{{ numbers | unique }}"