- name: filters/functions 
  hosts: local 
  connection: local 
  tasks: 
  - name: print the default variables 
    ansible.builtin.debug:
      msg: "Hello {{ my_name | default('chinni') }}"   # here my_name is not defined earlier 


  - name: convert the string into uppercase 
    vars: 
      my_name: "chinni"
    ansible.builtin.debug:
     msg: "{{ my_name | upper }}"

  - name: convert the string into lowercase 
    vars: 
      my_name: "MAHA"
    ansible.builtin.debug:
     msg: "{{ my_name | lower }}"

  - name: print the unique numbers 
    vars: 
      numbers: [17,45,7,8,234,17,45,7,8,234,5,56,6,7,23,234]
    ansible.builtin.debug:
     msg: "{{ numbers | unique }}"

  - name: printing max and min numbers 
    vars: 
      numbers: [17,45,7,8,234,17,45,7,8]
    ansible.builtin.debug:
     msg: "Min_number: {{ numbers | min }}, Max_number: {{ numbers | max }}"

  - name: converting map to list 
    vars: 
      self_intro:
        my_name: "chinni"
        address: "hyd"
        age: 25 
    ansible.builtin.debug:
     msg: "{{ self_intro | dict2items }}"

  - name: converting list to map 
    vars: 
      self_intro:
       - {"key": "my_name","value":"chinni"}
       - {"key": "address","value":"hyd"}
       - {"key": "age","value":"25"}
    ansible.builtin.debug:
     msg: "{{ self_intro | items2dict }}"
  
  - name: checking IP address
    vars: 
      ip: "192.168.1.2"   # if we given public ip it gives you false 
    ansible.builtin.debug:
     msg: "{{ ip | ansible.utils.ipv4 }}"