# - name: iterating the items
#   hosts: local 
#   connection: local 
#   tasks: 
#   - name: iterate over the items
#     ansible.builtin.debug:
#       msg: "{{ item }}"
#     loop:
#     - lakshmi 
#     - maha 
#     - mkml
#     - kml 
#     - chinni 
    

# - name: installing packages
#   hosts: web
#   become: yes 
#   tasks: 
#   - name: installing packages
#     ansible.builtin.package:
#       name: "{{ item }}"
#     loop:
#     - mysql 
#     - git 
#     - nginx 

- name: installing packages
  hosts: web
  become: yes 
  tasks: 
  - name: installing packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'present'}
    - { name: 'postfix', state: 'absent'}
    - { name: 'nginx', state: 'present'}
    - { name: 'httpd', state: 'absent'}